### ISSUE TITLE
USER STORY: <TITLE>

### ISSUE THREAD

**Issue by Sdalsosa** [Sdalsosa/Agile-Demo#5]
As a **site admin** I can **view the poll results** so that **I can understand what users prefer**

## Acceptance Criteria
- Acceptance Criteria 1: Be able to access the poll results
- Acceptance Criteria 2: Be able to see the user details if they didn't select the anonymous submission checkbox
- Acceptance Criteria 3: Be able to view poll stats

## Tasks
- [X] Task 1: Create a google sheet containing the poll results
- [ ] Task 2: Show user details on those who allowed their details
- [ ] Task 3: Generate statistics and graphs of the results automatically
